[2025-03-24T10:59:58.600+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T10:59:58.619+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dlt_to_postgres_pipeline.run_dlt_pipeline_task manual__2025-03-24T10:59:55.760260+00:00 [queued]>
[2025-03-24T10:59:58.628+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dlt_to_postgres_pipeline.run_dlt_pipeline_task manual__2025-03-24T10:59:55.760260+00:00 [queued]>
[2025-03-24T10:59:58.632+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-24T10:59:58.650+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_dlt_pipeline_task> on 2025-03-24 10:59:55.760260+00:00
[2025-03-24T10:59:58.656+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=826) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T10:59:58.658+0000] {standard_task_runner.py:72} INFO - Started process 828 to run task
[2025-03-24T10:59:58.658+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dlt_to_postgres_pipeline', 'run_dlt_pipeline_task', 'manual__2025-03-24T10:59:55.760260+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dlt_pipeline_dag.py', '--cfg-path', '/tmp/tmpe9_33j3x']
[2025-03-24T10:59:58.660+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask run_dlt_pipeline_task
[2025-03-24T10:59:58.909+0000] {task_command.py:467} INFO - Running <TaskInstance: dlt_to_postgres_pipeline.run_dlt_pipeline_task manual__2025-03-24T10:59:55.760260+00:00 [running]> on host e8d19883ae5b
[2025-03-24T10:59:58.994+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dlt_to_postgres_pipeline' AIRFLOW_CTX_TASK_ID='run_dlt_pipeline_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T10:59:55.760260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T10:59:55.760260+00:00'
[2025-03-24T10:59:58.995+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-24T10:59:58.996+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-24T10:59:58.997+0000] {logging_mixin.py:190} INFO - Current task name:run_dlt_pipeline_task state:running start_date:2025-03-24 10:59:58.620124+00:00
[2025-03-24T10:59:58.998+0000] {logging_mixin.py:190} INFO - Dag name:dlt_to_postgres_pipeline and current dag run status:running
[2025-03-24T10:59:58.998+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T10:59:59.000+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dlt_pipeline_dag.py", line 11, in run_dlt_pipeline
    from pipeline import pipeline_main
ModuleNotFoundError: No module named 'pipeline'
[2025-03-24T10:59:59.017+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-24T10:59:59.018+0000] {logging_mixin.py:190} INFO - Task start:2025-03-24 10:59:58.620124+00:00 end:2025-03-24 10:59:59.017170+00:00 duration:0.397046
[2025-03-24T10:59:59.018+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_dlt_pipeline_task> dag:<DAG: dlt_to_postgres_pipeline> dagrun:<DagRun dlt_to_postgres_pipeline @ 2025-03-24 10:59:55.760260+00:00: manual__2025-03-24T10:59:55.760260+00:00, state:running, queued_at: 2025-03-24 10:59:55.777063+00:00. externally triggered: True>
[2025-03-24T10:59:59.019+0000] {logging_mixin.py:190} INFO - Failure caused by No module named 'pipeline'
[2025-03-24T10:59:59.019+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=dlt_to_postgres_pipeline, task_id=run_dlt_pipeline_task, run_id=manual__2025-03-24T10:59:55.760260+00:00, execution_date=20250324T105955, start_date=20250324T105958, end_date=20250324T105959
[2025-03-24T10:59:59.054+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T10:59:59.055+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task run_dlt_pipeline_task (No module named 'pipeline'; 828)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dlt_pipeline_dag.py", line 11, in run_dlt_pipeline
    from pipeline import pipeline_main
ModuleNotFoundError: No module named 'pipeline'
[2025-03-24T10:59:59.075+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T10:59:59.267+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T10:59:59.269+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
